/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs3.h"

bool_t
xdr_uint64(xdrs, objp)
	XDR *xdrs;
	uint64 *objp;
{

	if (!xdr_u_int64_t(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int64(xdrs, objp)
	XDR *xdrs;
	int64 *objp;
{

	if (!xdr_int64_t(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_uint32(xdrs, objp)
	XDR *xdrs;
	uint32 *objp;
{

	if (!xdr_u_long(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_int32(xdrs, objp)
	XDR *xdrs;
	int32 *objp;
{

	if (!xdr_long(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_filename3(xdrs, objp)
	XDR *xdrs;
	filename3 *objp;
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfspath3(xdrs, objp)
	XDR *xdrs;
	nfspath3 *objp;
{

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fileid3(xdrs, objp)
	XDR *xdrs;
	fileid3 *objp;
{

	if (!xdr_uint64(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cookie3(xdrs, objp)
	XDR *xdrs;
	cookie3 *objp;
{

	if (!xdr_uint64(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_cookieverf3(xdrs, objp)
	XDR *xdrs;
	cookieverf3 objp;
{

	if (!xdr_opaque(xdrs, objp, 8))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_createverf3(xdrs, objp)
	XDR *xdrs;
	createverf3 objp;
{

	if (!xdr_opaque(xdrs, objp, 8))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_writeverf3(xdrs, objp)
	XDR *xdrs;
	writeverf3 objp;
{

	if (!xdr_opaque(xdrs, objp, 8))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_uid3(xdrs, objp)
	XDR *xdrs;
	uid3 *objp;
{

	if (!xdr_uint32(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_gid3(xdrs, objp)
	XDR *xdrs;
	gid3 *objp;
{

	if (!xdr_uint32(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_size3(xdrs, objp)
	XDR *xdrs;
	size3 *objp;
{

	if (!xdr_uint64(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_offset3(xdrs, objp)
	XDR *xdrs;
	offset3 *objp;
{

	if (!xdr_uint64(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_mode3(xdrs, objp)
	XDR *xdrs;
	mode3 *objp;
{

	if (!xdr_uint32(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_count3(xdrs, objp)
	XDR *xdrs;
	count3 *objp;
{

	if (!xdr_uint32(xdrs, objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfsstat3(xdrs, objp)
	XDR *xdrs;
	nfsstat3 *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_ftype3(xdrs, objp)
	XDR *xdrs;
	ftype3 *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_specdata3(xdrs, objp)
	XDR *xdrs;
	specdata3 *objp;
{

	if (!xdr_uint32(xdrs, &objp->specdata1))
		return (FALSE);
	if (!xdr_uint32(xdrs, &objp->specdata2))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfs_fh3(xdrs, objp)
	XDR *xdrs;
	nfs_fh3 *objp;
{

	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, 64))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_nfstime3(xdrs, objp)
	XDR *xdrs;
	nfstime3 *objp;
{

	if (!xdr_uint32(xdrs, &objp->seconds))
		return (FALSE);
	if (!xdr_uint32(xdrs, &objp->nseconds))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_fattr3(xdrs, objp)
	XDR *xdrs;
	fattr3 *objp;
{

	if (!xdr_ftype3(xdrs, &objp->type))
		return (FALSE);
	if (!xdr_mode3(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_uint32(xdrs, &objp->nlink))
		return (FALSE);
	if (!xdr_uid3(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_gid3(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_size3(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_size3(xdrs, &objp->used))
		return (FALSE);
	if (!xdr_specdata3(xdrs, &objp->rdev))
		return (FALSE);
	if (!xdr_uint64(xdrs, &objp->fsid))
		return (FALSE);
	if (!xdr_fileid3(xdrs, &objp->fileid))
		return (FALSE);
	if (!xdr_nfstime3(xdrs, &objp->atime))
		return (FALSE);
	if (!xdr_nfstime3(xdrs, &objp->mtime))
		return (FALSE);
	if (!xdr_nfstime3(xdrs, &objp->ctime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_post_op_attr(xdrs, objp)
	XDR *xdrs;
	post_op_attr *objp;
{

	if (!xdr_bool(xdrs, &objp->attributes_follow))
		return (FALSE);
	switch (objp->attributes_follow) {
	case TRUE:
		if (!xdr_fattr3(xdrs, &objp->post_op_attr_u.attributes))
			return (FALSE);
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_wcc_attr(xdrs, objp)
	XDR *xdrs;
	wcc_attr *objp;
{

	if (!xdr_size3(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_nfstime3(xdrs, &objp->mtime))
		return (FALSE);
	if (!xdr_nfstime3(xdrs, &objp->ctime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_pre_op_attr(xdrs, objp)
	XDR *xdrs;
	pre_op_attr *objp;
{

	if (!xdr_bool(xdrs, &objp->attributes_follow))
		return (FALSE);
	switch (objp->attributes_follow) {
	case TRUE:
		if (!xdr_wcc_attr(xdrs, &objp->pre_op_attr_u.attributes))
			return (FALSE);
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_wcc_data(xdrs, objp)
	XDR *xdrs;
	wcc_data *objp;
{

	if (!xdr_pre_op_attr(xdrs, &objp->before))
		return (FALSE);
	if (!xdr_post_op_attr(xdrs, &objp->after))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_post_op_fh3(xdrs, objp)
	XDR *xdrs;
	post_op_fh3 *objp;
{

	if (!xdr_bool(xdrs, &objp->handle_follows))
		return (FALSE);
	switch (objp->handle_follows) {
	case TRUE:
		if (!xdr_nfs_fh3(xdrs, &objp->post_op_fh3_u.handle))
			return (FALSE);
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_time_how(xdrs, objp)
	XDR *xdrs;
	time_how *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_set_mode3(xdrs, objp)
	XDR *xdrs;
	set_mode3 *objp;
{

	if (!xdr_bool(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case TRUE:
		if (!xdr_mode3(xdrs, &objp->set_mode3_u.mode))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_set_uid3(xdrs, objp)
	XDR *xdrs;
	set_uid3 *objp;
{

	if (!xdr_bool(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case TRUE:
		if (!xdr_uid3(xdrs, &objp->set_uid3_u.uid))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_set_gid3(xdrs, objp)
	XDR *xdrs;
	set_gid3 *objp;
{

	if (!xdr_bool(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case TRUE:
		if (!xdr_gid3(xdrs, &objp->set_gid3_u.gid))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_set_size3(xdrs, objp)
	XDR *xdrs;
	set_size3 *objp;
{

	if (!xdr_bool(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case TRUE:
		if (!xdr_size3(xdrs, &objp->set_size3_u.size))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_set_atime(xdrs, objp)
	XDR *xdrs;
	set_atime *objp;
{

	if (!xdr_time_how(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdr_nfstime3(xdrs, &objp->set_atime_u.atime))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_set_mtime(xdrs, objp)
	XDR *xdrs;
	set_mtime *objp;
{

	if (!xdr_time_how(xdrs, &objp->set_it))
		return (FALSE);
	switch (objp->set_it) {
	case SET_TO_CLIENT_TIME:
		if (!xdr_nfstime3(xdrs, &objp->set_mtime_u.mtime))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_sattr3(xdrs, objp)
	XDR *xdrs;
	sattr3 *objp;
{

	if (!xdr_set_mode3(xdrs, &objp->mode))
		return (FALSE);
	if (!xdr_set_uid3(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_set_gid3(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_set_size3(xdrs, &objp->size))
		return (FALSE);
	if (!xdr_set_atime(xdrs, &objp->atime))
		return (FALSE);
	if (!xdr_set_mtime(xdrs, &objp->mtime))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_diropargs3(xdrs, objp)
	XDR *xdrs;
	diropargs3 *objp;
{

	if (!xdr_nfs_fh3(xdrs, &objp->dir))
		return (FALSE);
	if (!xdr_filename3(xdrs, &objp->name))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GETATTR3args(xdrs, objp)
	XDR *xdrs;
	GETATTR3args *objp;
{

	if (!xdr_nfs_fh3(xdrs, &objp->object))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GETATTR3resok(xdrs, objp)
	XDR *xdrs;
	GETATTR3resok *objp;
{

	if (!xdr_fattr3(xdrs, &objp->obj_attributes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_GETATTR3res(xdrs, objp)
	XDR *xdrs;
	GETATTR3res *objp;
{

	if (!xdr_nfsstat3(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS3_OK:
		if (!xdr_GETATTR3resok(xdrs, &objp->GETATTR3res_u.resok))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_sattrguard3(xdrs, objp)
	XDR *xdrs;
	sattrguard3 *objp;
{

	if (!xdr_bool(xdrs, &objp->check))
		return (FALSE);
	switch (objp->check) {
	case TRUE:
		if (!xdr_nfstime3(xdrs, &objp->sattrguard3_u.obj_ctime))
			return (FALSE);
		break;
	case FALSE:
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_SETATTR3args(xdrs, objp)
	XDR *xdrs;
	SETATTR3args *objp;
{

	if (!xdr_nfs_fh3(xdrs, &objp->object))
		return (FALSE);
	if (!xdr_sattr3(xdrs, &objp->new_attributes))
		return (FALSE);
	if (!xdr_sattrguard3(xdrs, &objp->guard))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_SETATTR3resok(xdrs, objp)
	XDR *xdrs;
	SETATTR3resok *objp;
{

	if (!xdr_wcc_data(xdrs, &objp->obj_wcc))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_SETATTR3resfail(xdrs, objp)
	XDR *xdrs;
	SETATTR3resfail *objp;
{

	if (!xdr_wcc_data(xdrs, &objp->obj_wcc))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_SETATTR3res(xdrs, objp)
	XDR *xdrs;
	SETATTR3res *objp;
{

	if (!xdr_nfsstat3(xdrs, &objp->status))
		return (FALSE);
	switch (objp->status) {
	case NFS3_OK:
		if (!xdr_SETATTR3resok(xdrs, &objp->SETATTR3res_u.resok))
			return (FALSE);
		break;
	default:
		if (!xdr_SETATTR3resfail(xdrs, &objp->SETATTR3res_u.resfail))
			return (FALSE);
		break;
	}
	return (TRUE);
}
